name: Go CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching vX[.X[.X]], i.e. v20, v20.15, v20.15.10
  pull_request:
    branches:
      - '**'

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
